quarkus.application.name=eip-feature-flags

kafka.brokers=localhost:9092
quarkus.http.port=8096
quarkus.kafka.devservices.enabled=false

# flagd, from the Podman stack
flagd.host=localhost
flagd.port=8013

quarkus.log.category."com.example.eip".level=INFO
