spring.application.name=eip-feature-flags

kafka.brokers=localhost:9092
server.port=8096

# flagd, from the Podman stack
flagd.host=localhost
flagd.port=8013

logging.level.com.example.eip=INFO
camel.main.run-controller=true
